# Generated by Django 4.2.7 on 2023-11-28 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_produc_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(
                choices=[
                    ("computer", "Computer"),
                    ("airpod", "Air Pod"),
                    ("iwatch", "iWatch"),
                ],
                max_length=200,
            ),
        ),
    ]
