# Generated by Django 4.2.7 on 2023-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_options_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnail/"),
        ),
    ]
